# Generated by Django 4.1.7 on 2023-03-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='media',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
