# Generated by Django 4.1.7 on 2023-03-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioWebsite', '0002_project_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
